### ISSUE TITLE
entity-server generator does not work without entity

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster-blueprint#10]
I used this blueprint to generate my blueprint.  At first I the only option I chose was "entity-server". 

I tried to trigger the blueprint without success for few hours. Then, looking at the jhipster-kotlin example I added the "entity/index.js" file copied from jhipster-kotlin blueprint. This change apparently  made everithing work as expected.

I don't know if this is an expected behaviour. If so, I suggest to add the "entity/index.js" file when choosing entity-server or entity-client from the list of the options.

Hope this is the right place to discuss this, otherwise I can move the discussion on generator-jhipster repo.

Thank you

**Comment by deepu105** [comment]
I'll have a  look

Thanks & Regards,
Deepu

**Comment by murdos** [comment]
I have actually similar issues while trying to generate samples unit tests (#7): the sub-generators `entity-server`, `entity-client` and `entity-i18n` seem to highly depend on the `entity ` subgenerator and can't be run independently:
```
  3) Subgenerator entity-server of helloworld JHipster blueprint
       Sample test
         "before all" hook:
     Uncaught TypeError: Cannot read property 'isDebugEnabled' of undefined
      at new module.exports (node_modules\generator-jhipster\generators\entity-server\index.js:40:37)
      at Environment.instantiate (node_modules\yeoman-environment\lib\environment.js:408:12)
```

@deepu105 : Could you confirm that? I've noticed that there are no unit tests in jhipster for these subgenerators (only tests for entity). Does that mean that this generator should be changed to force the generation of the entity subgenerator if any "child" (-i18n, -client or -server) subgen is chosen?

PS: I've uploaded the result of my current work here: https://github.com/murdos/generator-jhipster-blueprint-example-with-tests/tree/master/test

**Comment by deepu105** [comment]
My idea was to have them as independent so you don't have to override the everything but somehow it doesn't seem to work. And when I tried to add unit tests for this, it wasn't working as well and thats why didn't commit it. Currently I'm tight on schedule to look at this. If you have time and are willing then would love to find a solution

**Comment by murdos** [comment]
Alright, thanks. I'll then try to add unit tests for core subgen in jhipster as a first step. Then we'll see what could be done for blueprint and blueprint unit tests.
