### ISSUE TITLE
Use new blueprint base API

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster-blueprint#19]
Since version 5.7 of generator-jhipster, all subgenerators have a base API that need to be extended in all subgenerators of a blueprint.

**Comment by avdev4j** [comment]
I think @murdos you can close this one since all subgenerators "blueprintable" are extending `BaseBlueprintGenerator`. 👍

**Comment by murdos** [comment]
The ticket description might not been very clear :)
In fact each subgenerator should declare and delegate by default to jhipster each existing yeoman step: https://github.com/jhipster/generator-jhipster/pull/8623#discussion_r226876596

**Comment by avdev4j** [comment]
my bad.
I did not understood. Do you have an idea of the amount of task remain to do ? I probably can help you.

**Comment by murdos** [comment]
In fact my original plan was to rewrite this yeoman generator to only use one template for all subgenerators, rather than one template per subgenerator (excepted maybe for `client`, its content is a bit different).
There's indeed currently a lot of duplicated code and redundancy in these templates.
In this plan I would have solved this ticket, and #18 in the same time.

But I'm currently a bit busy, so if you want to work on it, you're welcome :)

**Comment by avdev4j** [comment]
Using only one template seems not to be very hard to do but indeed it need time.
I probably take a look about this after I have finished all my current PR on the main generator ;).

**Comment by murdos** [comment]
Fixed with https://github.com/jhipster/generator-jhipster-blueprint/pull/26
