### ISSUE TITLE
TypeError: require(...).requirePackage is not a function

### ISSUE THREAD

**Issue by huicha** [jhipster/generator-jhipster-blueprint#21]
my jhipster version is 5.7.2 and is working okay! but when I want to try with the blueprint generator I got this message.

yo jhipster-blueprint
/usr/local/lib/node_modules/generator-jhipster-blueprint/node_modules/errlop/index.js:4
module.exports = require('editions').requirePackage(__dirname, require)
                                     ^

TypeError: require(...).requirePackage is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-blueprint/node_modules/errlop/index.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-blueprint/node_modules/editions/edition-node-0.8/index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
--------------
node -v
v10.15.0
--------------
npm -v
6.4.1
--------------
yo --version
2.0.5

yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ yo version

Everything looks all right!
--------------

**Comment by pascalgrimaud** [comment]
@huicha : which version of the blueprint do you use ? the last release or the master from this repo ?

**Comment by huicha** [comment]
@pascalgrimaud  I have installed the last release

**Comment by pascalgrimaud** [comment]
Just tested and it works well for me.

I installed the last release:

```
19:18:48 in .npm-global/lib/node_modules 
➜ npm install -g generator-jhipster-blueprint
+ generator-jhipster-blueprint@0.0.9
added 340 packages from 230 contributors in 3.016s

19:18:54 in .npm-global/lib/node_modules took 4s 
➜ l
total 20K
drwxrwxr-x  5 pgrimaud pgrimaud 4,0K déc.  28 19:18 .
drwxrwxr-x  3 pgrimaud pgrimaud 4,0K nov.  27 21:21 ..
lrwxrwxrwx  1 pgrimaud pgrimaud   51 déc.  27 19:44 generator-jhipster -> /home/pgrimaud/projects/jhipster/generator-jhipster
drwxrwxr-x  4 pgrimaud pgrimaud 4,0K déc.  28 19:18 generator-jhipster-blueprint
lrwxrwxrwx  1 pgrimaud pgrimaud   58 nov.  27 21:48 generator-jhipster-module -> /home/pgrimaud/projects/jhipster/generator-jhipster-module
lrwxrwxrwx  1 pgrimaud pgrimaud   47 déc.  27 19:44 generator-jhipster-vuejs -> /home/pgrimaud/projects/jhipster/jhipster-vuejs
drwxr-xr-x 10 pgrimaud pgrimaud 4,0K déc.  20 07:52 npm
drwxrwxr-x  4 pgrimaud pgrimaud 4,0K nov.  27 21:24 yo
```

Then, in an **empty** folder, I launch the creation of a new blueprint:
```
19:18:59 in ~/tmp/jhipster-xmas 
➜ yo jhipster-blueprint
         http://www.jhipster.tech

Welcome to the JHipster Blueprint Generator! v0.0.9

? What is the base name of your module? xmas
? Give a description of your module xmas
? Which sub-generators do you want to override? server
? What is your GitHub username? pascalgrimaud
? Who are you? Firstname Lastname Pascal Grimaud
? Your email? 
? Your home page url? 
? Do you want to add a license? Apache License 2.0
[ 'server' ]
   create package.json
   create .editorconfig
   create .eslintignore
   create .eslintrc.json
   create .prettierrc
   create .prettirignore
   create .gitattributes
   create .gitignore
   create .travis.yml
   create LICENSE
   create README.md
   create generators/server/index.js
   create test/server.spec.js

##### USAGE #####
To begin to work:
- launch: yarn install or npm install
- link: yarn link or npm link
- link JHipster: yarn link generator-jhipster or npm link generator-jhipster
- test your module in a JHipster project: 
    - create a new directory and go into it
    - link the blueprint: yarn link generator-jhipster-xmas or npm link generator-jhipster-xmas
    - launch JHipster with flags: jhipster --blueprint xmas
- then, come back here, and begin to code!


19:19:25 in ~/tmp/jhipster-xmas took 23s 
➜ l
total 72K
drwxrwxr-x  4 pgrimaud pgrimaud 4,0K déc.  28 19:19 .
drwxrwxr-x 27 pgrimaud pgrimaud 4,0K déc.  28 19:17 ..
-rw-rw-r--  1 pgrimaud pgrimaud  268 déc.  28 19:19 .editorconfig
-rw-rw-r--  1 pgrimaud pgrimaud   58 déc.  28 19:19 .eslintignore
-rw-rw-r--  1 pgrimaud pgrimaud 1,1K déc.  28 19:19 .eslintrc.json
drwxrwxr-x  3 pgrimaud pgrimaud 4,0K déc.  28 19:19 generators
-rw-rw-r--  1 pgrimaud pgrimaud  434 déc.  28 19:19 .gitattributes
-rw-rw-r--  1 pgrimaud pgrimaud  147 déc.  28 19:19 .gitignore
-rw-rw-r--  1 pgrimaud pgrimaud  12K déc.  28 19:19 LICENSE
-rw-rw-r--  1 pgrimaud pgrimaud 2,2K déc.  28 19:19 package.json
-rw-rw-r--  1 pgrimaud pgrimaud  110 déc.  28 19:19 .prettierrc
-rw-rw-r--  1 pgrimaud pgrimaud   30 déc.  28 19:19 .prettirignore
-rw-rw-r--  1 pgrimaud pgrimaud 2,6K déc.  28 19:19 README.md
drwxrwxr-x  2 pgrimaud pgrimaud 4,0K déc.  28 19:19 test
-rw-rw-r--  1 pgrimaud pgrimaud  150 déc.  28 19:19 .travis.yml
-rw-rw-r--  1 pgrimaud pgrimaud  193 déc.  28 19:19 .yo-rc.json
```

**Comment by huicha** [comment]
Yes, you are right. I did the same and it worked well. <.<
Thank you for your time!

**Comment by pascalgrimaud** [comment]
Nice ! Don't hesitate to notify `@java_hipster` on Twitter if you start a blueprint :-)

As it is solved, I'm closing this ticket.
