### ISSUE TITLE
entity-server generator import problems with writeFiles function

### ISSUE THREAD

**Issue by Kerruba** [jhipster/generator-jhipster-blueprint#29]
Hello,
I'm trying to develop a blueprint with just an entity, entity-server and server generators.

In my entity-server generator, I'm trying to use a separate module to import files, and this module contains a function named `writeFiles` which basically write all the required files in the final app. I 
When I require such function in my `entity-server/index.js` file, instead of using my own personal custom steps, jhipster uses the regular `entity-server` steps. 

What is even stranger is that if I manually update the `get writing()` property of the generator, nothing happens until I remove the import statement. Only in that case, what I write inside the `get writing()` step is triggered.

Could this be related to the name of my function? Any suggestion?

**Comment by avdev4j** [comment]
Hi @Kerruba 
I'm not sure to understand your problem while I can't read your code.

Please add some codes and I'll check it.

**Comment by Kerruba** [comment]
It's quite weird but today is working, I don't know if it's because there was an error in my code and it wasn't pickup correctly the file, but today is working. Sorry that I bothered you with this! If for any reason this would happen again, I'll bring this up once again
