### ISSUE TITLE
Composing or using multiple blueprints

### ISSUE THREAD

**Issue by hermitmaster** [jhipster/generator-jhipster-blueprint#31]
Is there currently a defined method for using multiple blueprints when running jhipster? I assume, no. Additionally, is there a method to extend or import a blueprint in another blueprint?

**Comment by deepu105** [comment]
Not at the moment as its a bit difficult to do this with the way current architecture and yeoman works.

**Comment by 62mkv** [comment]
hopefully there're plans to make Vue.js just an aspect of application that has UI part (like currently with Angular/React) and Kotlin an aspect of an application for the backend ?

**Comment by hermitmaster** [comment]
We're a Groovy shop, so I'd be looking for Groovy and Vue.js.

**Comment by 62mkv** [comment]
well, Kotlin and Vue.js are at least *official* blueprints.. so hopefully this should be achievable

**Comment by pvliss** [comment]
@jhipster/developers Are we interested in implementing this? I could take at look at it if you don't mind and believe it is worth it. The only problem I see currently is the use of inheritance for blueprints and think that we should use aggregation instead if possible. Any thoughts?  

PS: I think that this issue should be moved to https://github.com/jhipster/generator-jhipster

**Comment by pascalgrimaud** [comment]
Clearly, yes @pvliss and it probably deserves a bug bounty on this, as it is a big wanted feature !
What do you think @jdubois about the bug bounty ?

**Comment by pvliss** [comment]
Cool. 

Any thoughts about switching to aggregation instead? Should be doable but I am afraid it would break compatibility with existing blueprints...

**Comment by hermitmaster** [comment]
I'd agree with aggregation, but it could get tricky when multiple blueprints overlap.

**Comment by pascalgrimaud** [comment]
I'd like something:
- jhipster --blueprint vuejs,kotlin

The list of blueprint should respect priority. 
If we find server subgen in vuejs, it will use it. 
Otherwise, it will check in kotlin
Then, use the default one in generator

**Comment by pvliss** [comment]
That's true but the same would happen with inheritance as well.  One way to avoid that in case of overlapping blueprints/generators could be the addition of an order property, although I am not sure how many blueprints actually overlap and if you want to use more than one in that case. So if say you have both a kotlin and groovy blueeprint you would only use one of them. Supplementary blueprints should not overlap anyways. Do you have something other use case in mind?

**Comment by pvliss** [comment]
> I'd like something:
> 
>     * jhipster --blueprint vuejs,kotlin
> 
> 
> The list of blueprint should respect priority.
That is what I had in mind as well.

> If we find server subgen in vuejs, it will use it.
> Otherwise, it will check in kotlin
> Then, use the default one in generator
As per my previous comment I am not sure of how common that would be but then again I believe we can implement that as well, i.e. check if gen exists and only apply first one in case of multiple.

**Comment by hermitmaster** [comment]
Something like that seems reasonable. Would it make sense to draw a distinction between front-end and backend blueprints?

**Comment by pvliss** [comment]
Well they are already separate sub-generators so not sure what extra distinctions should be made. If you are talking about using an extra property to mark them as such I don't believe its currently necessary. At least not for the generator. Maybe for categorization purposes and display/filtering at https://www.jhipster.tech/modules/marketplace/#/list

**Comment by hermitmaster** [comment]
Basically adding semantics to prevent nonsensical aggregates.

**Comment by avdev4j** [comment]
Hi team,
This subject is in my mind for few weeks now. I plan to combine blueprints and I wonder how.
The main risk is that two blueprints modify the same files and cause a bug. 

We can :
- Disallow some blueprints to be combine if they override same sub-generators => for me it's not the way to go but it should work fine with kotlin and vuejs, except if both override common or language sub-generator :D.
- Allow blueprints to be combines, whatever they overriden, and trust our users to use this efficiently (maybe display a warning message).
- Or use the @pascalgrimaud way and use priority.

In my case I want to use a blueprint with client sub-generator (which update some config stuff) and a blueprint which add angular-material. They override the same sub-generator but not for the same reason.

**Comment by deepu105** [comment]
I had this in mind when I originally wrote vthe feature but decided to
leave it out due to complexity. I do agree on the necessity. A simpler way
to start would be to iterate over the blueprints specified and use the
implementation from the last one specified (override behaviour)

**Comment by avdev4j** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/9937
