### ISSUE TITLE
Blueprint to limit the application type

### ISSUE THREAD

**Issue by Kerruba** [jhipster/generator-jhipster-blueprint#37]
Hello, 

I'm working on developing a blueprint using JHipster but I would like to limit the application Type as the blueprint should only be able to create microservices application. At the moment is not possible with a blueprint to modify/limit the application type but would it make sense to add this functionality to the blueprint? or is something that should be embedded in jhipster-core?

**Comment by murdos** [comment]
Hi @Kerruba
We have some discussion on https://github.com/jhipster/generator-jhipster/issues/9692 that relates to your need. It's indeed something that should be done in `generator-jhipster`

**Comment by sendilkumarn** [comment]
@Kerruba You can do that with customising the prompts.

**Comment by Kerruba** [comment]
@sendilkumarn you can't modify the prompts for the app-generator as that is not extensible. 
Though yeah is possible to add custom prompts to the server generator for example, but I don't think is very clean and elegant: what if a user choose monolith and we then tell them you're application is a micro-service?
As @murdos suggested, there's already an issue open in the `generator-jhipster` repo and probably that's where this issue belongs to :-)

**Comment by sendilkumarn** [comment]
> Though yeah is possible to add custom prompts to the server generator for example, but I don't think is very clean and elegant: what if a user choose monolith and we then tell them you're application is a micro-service?


You should not override the server only but the app too. You have to add an override for the `app` in the blueprint and use everything from the base generator except for the `askForApplicationType` method to which we can add the custom method.

(This prompts file)[https://github.com/jhipster/generator-jhipster/blob/b1925bbe9283d4502d749d829fa1793afb1605e8/generators/app/prompts.js]

Technically it is possible with some extensions and composing.

**Comment by Kerruba** [comment]
@sendilkumarn from the documentation what I understand is that the app-generator is not extensible
> A blueprint can only extend the following sub-generators (under the generators folder)
common
client
server
entity
entity-client
entity-server
entity-i18n
languages
spring-controller
spring-service

But maybe I'm not understanding properly your approach. Are you suggesting to use directly the blueprint as a yeoman generator instead of a jhispter bluepring - i.e. calling the generator with `yo generator-jhister-mycustomblueprint` instead of `jhispter --blueprint mycustombluprint`?

**Comment by deepu105** [comment]
Yes at the moment you cannot extend the app generator. This needs to be
looked into

**Comment by avdev4j** [comment]
I since this PR has been merged we can close this issue.
https://github.com/jhipster/generator-jhipster/pull/10752
