### ISSUE TITLE
entity-client default generator not working

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster-blueprint#38]
I have been trying to use entity-client generator without luck for few days, after a lot of debugging I found out the source of the problem.
The generated code:
```
super(args, Object.assign({ fromBlueprint: true }, opts)); // fromBlueprint variable is important

        const jhContext = (this.jhipsterContext = this.options.jhipsterContext);

        if (!jhContext) {
            this.error(`This is a JHipster blueprint and should be used only like ${chalk.yellow('jhipster --blueprint primeng')}`);
        }

        this.configOptions = jhContext.configOptions || {};
```

This works well for client, but in the constructor of `EntityClientGenerator` `super` we have:
`utils.copyObjectProps(this, this.options.context);`
which overrides `this.options` with `this.options.context.options` losing the reference of options
My workaround is retrieving it from opts param: `const jhContext = (this.jhipsterContext = opts.jhipsterContext);` I hope this doesn't mess up how stuff should work add that all options are passed correctly, but this definitely should be fixed, maybe by modifying `EntityClientGenerator` so that options don't get overridden. I don't have enough knowledge of the generator's code to know.

**Comment by pascalgrimaud** [comment]
@yelhouti : the entity client works well for Vuejs blueprint: https://github.com/jhipster/jhipster-vuejs

Maybe you can have a look there ?

**Comment by yelhouti** [comment]
@pascalgrimaud that is also my point, the blueprint works without all the checks in enerated blueprint, if they are not usefull, please remove them to avoid confusion, if they are (for cases where we want to partially override a phase) please correct them.

**Comment by pascalgrimaud** [comment]
I'm not expert enough in blueprint, but this part of code is probably here for a good reason.
cc @avdev4j as he knows this part better than me

**Comment by pascalgrimaud** [comment]
I'm not expert enough in blueprint, but this part of code is probably here for a good reason.
cc @avdev4j as he knows this part better than me

**Comment by avdev4j** [comment]
hi,
We have recently migrate all blueprint templates to a generic one. https://github.com/jhipster/generator-jhipster-blueprint/pull/26

Maybe we failed for the entity-client, but as I can see we put the same code for both.

The original entity-client had this, could you please test with that?
```    
constructor(args, opts) {
        super(args, Object.assign({ fromBlueprint: true }, opts)); // fromBlueprint variable is important

        const jhContext = (this.jhipsterContext = this.options.jhipsterContext);

        if (!jhContext) {
            this.error(
                `This is a JHipster blueprint and should be used only like ${chalk.yellow('jhipster --blueprint <%= moduleName %>')}`
            );
        }

        this.configOptions = jhContext.configOptions || {};
    }```

I feel it's the same but I am in a train so I can't test now.

**Comment by yelhouti** [comment]
@avdev4j indeed it's the same, it has the problem I'm trying to explain the initial comment.

**Comment by avdev4j** [comment]
After some search I wonder if it could be an oversight in this PR: https://github.com/jhipster/generator-jhipster/pull/7437

The entity-server was changed to use `opts.context`: https://github.com/jhipster/generator-jhipster/pull/7437/files#diff-e606891a5f420e4c77cf7e4ba7b787c4R30

While entity-client and entity-i18n kept `this.options.context`.

Is this is intended? I don't know. Maybe @deepu105 or @sendilkumarn could be help us to understand and fix that if needed.

**Comment by abocoum** [comment]
PS: sorry for my bad English it translate by bing !!!!
In my case My sub generator entity-client had an unraised runtime  error (dependency missing) so it was ignored. When I corrected it's OK.
How did the exception of this type of error be thrown? If anyone knows I'm a taker?

**Comment by yelhouti** [comment]
@abocoum this is a separate issue, please open a new issue.
I understand your problem, and it is not related to mine.
