### ISSUE TITLE
end() seems not been overwrited on client blueprint 

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster-blueprint#4]
Overview of the issue
The end() method (in index.js), when using a client blueprint, seems not been overwrited and only the parent method is called.

Environnement: 
> jHipster-generator: 5.0.1
> generator-jhipster-blueprint: 0.0.3
> OS: windows 7 64 bits
> yeoman: 2.0.1
> npm: 5.8.0
> nodejs: 8.10.0
> 

Reproduce the error
You can find my client blueprint generator here https://github.com/avdev4j/generator-jhipster-mergeBP
Just run it with `jhipster --skip-server --skip-install --auth --db --blueprint avdev4j` and see that at the end no specific log is displayed only the client generator one.

Expected:
end() message log

> Client application generated successfully.
> 
> Start your Webpack development server with:
>  yarn start
> i am a pretty log. Please display me !!!

Result:
end() message log

> Client application generated successfully.
> 
> Start your Webpack development server with:
>  yarn start

Even if my method return null, nothing, empty object the original text is always displayed. I turned it into many ways but never be able to display my log message so i decided to open an issue.

**Comment by pascalgrimaud** [comment]
Thanks for testing it @avdev4j ! We really need feedback

I have some questions:
- do you use Yarn or NPM
- did you apply correctly all yarn link or npm link

**Comment by pascalgrimaud** [comment]
@avdev4j : just tried it. Here all my steps:
- git clone https://github.com/avdev4j/generator-jhipster-mergeBP
- cd generator-jhipster-mergeBP
- yarn install
- yarn link

- cd ~/tmp
- mkcd 12-merge
- yarn link generator-jhipster-mergeBP
- jhipster --skip-server --skip-install --auth --db --blueprint mergeBP

Here the output. It seems working well :)

```
Client application generated successfully.

Start your Webpack development server with:
 yarn start

i am a pretty log. Please display me !!!
Congratulations, JHipster execution is complete!
Application successfully committed to Git.

```

**Comment by avdev4j** [comment]
Hi Pascal,
Thanks for your answer.
I have both npm and yarn but i use npm for this tests.

Before i wrote this issue i made some npm link to be sure it was not came from that. But you're right it seems to be an update issue.

the modifications i did were not visible when i launchmy blueprint.

To be honest i used to re-run the blueprint in the same folder without cleaning my old files (lazy developer ofc).
So after i see your reply i cleaned this directory, re launch and it's worked.

I'm not sure what happened but i suppose my generator in the "node_module" folder was not link the right one. I'm surprised because i did many "npm link" to be sur it was not came from that.

Thanks for the reply, i think we can close this issue :D.

**Comment by deepu105** [comment]
Here are the steps I'm adding in docs

During development of blueprint, please note the below steps. they are very important.

1. Link your blueprint globally (use npm since yeoman doesnt seem to fetch globally linked Yarn modules)

```bash
cd my-blueprint
npm link
```

2. Link a development version of JHipster to your blueprint (optional: required only if you want to use a non released JHipster version, like the master branch or your own custom fork)

You could also use Yarn for this if you prefer

```bash
cd generator-jhipster
npm link

cd my-blueprint
npm link generator-jhipster
```

3. Create new folder for the app to be generated and link JHipster and your blueprint there

```bash
mkdir my-app && cd my-app

npm link generator-jhipster-myblueprint
npm link generator-jhipster (Optional: Needed only if you are using a non released JHipster version)

jhipster -d --blueprint myblueprint

```

**Comment by deepu105** [comment]
@avdev4j can you try them and let me know if they work for you
