### ISSUE TITLE
release 0.3.0 or 0.2.x version

### ISSUE THREAD

**Issue by avdev4j** [jhipster/generator-jhipster-blueprint#66]
When #61 and #60 will be merged I suggest to do a new release of the generator and publish it to npm repository.

At least for the App configurator added.

I don't know how to do this but I'm sure we have experts here ;)

**Comment by pascalgrimaud** [comment]
I can do this, unless @murdos wants to check as he's the stream lead here

**Comment by murdos** [comment]
I'll do the release during the week-end. Before I would like to move the CI to GitHub Actions.

**Comment by avdev4j** [comment]
Ping me if you need help

**Comment by murdos** [comment]
Version 0.3.0 is released :)
