### ISSUE TITLE
Blueprint upgrade

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster-blueprint#95]
Hello folks,

I used the blueprint generator to instanciate the quarkus generator. 
I would like to know if there is any built-in mechanism to upgrade the `generator-blueprint`, like it's done with `jhipster upgrade`?
The purpose would be to ease the dependency upgrade.

**Comment by mshima** [comment]
I don't know if it's worth.
You can re-run the generator-jhipster-blueprint and hit yes only to package.json.
But I think we should keep the config stored for this.

**Comment by murdos** [comment]
I also don't think if it's worth.

**Comment by mshima** [comment]
@murdos I think we should keep this open for now.
We should save the config to easily allow to re-run without having to answer every question again.

**Comment by pascalgrimaud** [comment]
I agree with @murdos, not sure it's worth.
I don't know what we can do here.

The simplest way is to:
- create git branch
- launch `yo jhipster-blueprint`
- accept all
- then, use `git diff` to keep the custom code

I don't see any value to "code" these 4 steps...

**Comment by danielpetisme** [comment]
Sounds good to me. I think it worth to be documented at least but yes I'm totally fine with a manual upgrade.
